import { lookup } from "node:dns/promises";
import { isIP } from "node:net";

export type GoogleCandidate={companyName:string;websiteUrl?:string;city?:string;industry?:string;sourceUrl?:string};
export type WebsiteAudit={companyName:string;websiteUrl?:string;city?:string;industry?:string;sourceUrl?:string;checkedAt:string;status:"AUDITED"|"NO_WEBSITE"|"BLOCKED_URL"|"FETCH_ERROR";httpStatus?:number;finalUrl?:string;https?:boolean;title?:string;metaDescription?:string;hasViewportMeta?:boolean;hasContactPath?:boolean;hasEmailLink?:boolean;responseTimeMs?:number;flags:string[];note?:string};

const isPrivate4=(ip:string)=>{const p=ip.split(".").map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return true;const[a,b]=p;return a===0||a===10||a===127||a>=224||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===198&&(b===18||b===19))};
const isPublic=(ip:string)=>{const v=isIP(ip);if(v===4)return !isPrivate4(ip);if(v===6)return /^2[0-9a-f]{3}:/i.test(ip)&&!ip.toLowerCase().startsWith("2001:db8:");return false};
export async function isSafePublicUrl(raw:string){let u:URL;try{u=new URL(raw)}catch{return false}if(!["http:","https:"].includes(u.protocol)||u.username||u.password)return false;const h=u.hostname.toLowerCase().replace(/^\[|\]$/g,"");if(!h||h==="localhost"||h.endsWith(".localhost")||h.endsWith(".local"))return false;if(isIP(h))return isPublic(h);try{const a=await lookup(h,{all:true,verbatim:true});return a.length>0&&a.every(x=>isPublic(x.address))}catch{return false}}
const strip=(v:string)=>v.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const meta=(html:string,name:string)=>{for(const tag of html.match(/<meta\b[^>]*>/gi)??[]){const m=tag.match(/\b(?:name|property)\s*=\s*["']?([^\s"'/>]+)/i);if(m?.[1]?.toLowerCase()!==name)continue;const c=tag.match(/\bcontent\s*=\s*["']([^"']*)["']/i)??tag.match(/\bcontent\s*=\s*([^\s>]+)/i);if(c?.[1])return strip(c[1]).slice(0,300)}};
export function extractWebsiteSignals(html:string){const title=html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1],metaDescription=meta(html,"description"),hasViewportMeta=/<meta\b[^>]*name\s*=\s*["']?viewport\b/i.test(html),hasContactPath=/href\s*=\s*["'][^"']*(kontakt|contact|book|bestill|avtal|appointment)[^"']*["']/i.test(html),hasEmailLink=/href\s*=\s*["']mailto:/i.test(html),flags:string[]=[];if(!title||!strip(title))flags.push("MISSING_TITLE");if(!metaDescription)flags.push("MISSING_META_DESCRIPTION");if(!hasViewportMeta)flags.push("MISSING_VIEWPORT_META");if(!hasContactPath)flags.push("NO_OBVIOUS_CONTACT_PATH");if(!hasEmailLink)flags.push("NO_EMAIL_LINK_DETECTED");return{title:title?strip(title).slice(0,200):undefined,metaDescription,hasViewportMeta,hasContactPath,hasEmailLink,flags}};
async function fetchPage(start:string){let current=start;for(let i=0;i<=4;i++){if(!(await isSafePublicUrl(current)))throw new Error("URL_BLOCKED_OR_NON_PUBLIC");const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);let r:Response;try{r=await fetch(current,{redirect:"manual",signal:c.signal,headers:{"user-agent":"CideaWebsiteIntelligence/0.1"}})}finally{clearTimeout(t)}if([301,302,303,307,308].includes(r.status)){const loc=r.headers.get("location");await r.body?.cancel().catch(()=>undefined);if(!loc||i===4)throw new Error("REDIRECT_LIMIT");current=new URL(loc,current).toString();continue}return{r,current}}throw new Error("REDIRECT_LIMIT")}
export async function auditCandidate(candidate:GoogleCandidate):Promise<WebsiteAudit>{const checkedAt=new Date().toISOString(),base={...candidate,checkedAt};if(!candidate.websiteUrl)return{...base,status:"NO_WEBSITE",flags:["NO_WEBSITE"]};const started=Date.now();try{const{r,current}=await fetchPage(candidate.websiteUrl),ct=r.headers.get("content-type")??"";if(!ct.toLowerCase().includes("text/html"))return{...base,status:"AUDITED",httpStatus:r.status,finalUrl:current,https:new URL(current).protocol==="https:",responseTimeMs:Date.now()-started,flags:["NON_HTML_RESPONSE"]};const reader=r.body?.getReader();const chunks:Uint8Array[]=[];let total=0;while(reader&&total<512*1024){const{done,value}=await reader.read();if(done||!value)break;const c=value.slice(0,512*1024-total);chunks.push(c);total+=c.byteLength;if(c.byteLength<value.byteLength)break}await reader?.cancel().catch(()=>undefined);const bytes=new Uint8Array(total);let o=0;for(const c of chunks){bytes.set(c,o);o+=c.byteLength}const s=extractWebsiteSignals(new TextDecoder().decode(bytes)),flags=[...s.flags];if(r.status>=400)flags.unshift("HTTP_ERROR");if(new URL(current).protocol!=="https:")flags.push("NOT_HTTPS");return{...base,status:"AUDITED",httpStatus:r.status,finalUrl:current,https:new URL(current).protocol==="https:",responseTimeMs:Date.now()-started,...s,flags,note:"Automated signals only; review manually before qualifying this lead."}}catch(e){const blocked=e instanceof Error&&e.message==="URL_BLOCKED_OR_NON_PUBLIC";return{...base,status:blocked?"BLOCKED_URL":"FETCH_ERROR",responseTimeMs:Date.now()-started,flags:[blocked?"BLOCKED_URL":"FETCH_ERROR"],note:e instanceof Error?e.message:"Unknown error"}}}
export async function auditCandidates(candidates:GoogleCandidate[],concurrency=4){const results:WebsiteAudit[]=new Array(candidates.length);let next=0;await Promise.all(Array.from({length:Math.max(1,Math.min(Math.floor(concurrency),candidates.length||1))},async()=>{while(true){const i=next++;if(i>=candidates.length)return;results[i]=await auditCandidate(candidates[i]!)}}));return results}
